name: handling_network_connectivity
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"
dependencies:
  connectivity_plus: ^2.1.0
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  http: ^0.13.4
  stacked: ^2.2.7+1
  stacked_services: ^0.8.16

dev_dependencies:
  build_runner: ^2.1.7
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  stacked_generator: ^0.5.6
flutter:
  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
